SELECT MC.BEST_DATE
	,YEAR(MC.BEST_DATE) YEAR
	,MONTH(MC.BEST_DATE) MONTH
	,MC.DATABASE_NAME
	,VESSEL_NAME
	,VESSEL_REGISTRATION_NUMBER
	,FISHERY_SECTOR
	,MC.TRIP_ID
	,MC.FISHING_EVENT_ID
	,MC.MAJOR_STAT_AREA_CODE
	,MC.MINOR_STAT_AREA_CODE
	,MC.LOCALITY_CODE
	,LATITUDE
	,LONGITUDE
	,MC.GEAR
	,BEST_DEPTH
	,NUMBER_GEAR_SET HOOKS_SET
	,NUMBER_GEAR_LOST HOOKS_LOST
	,SKATE_LENGTH_FT
	,HOOK_TRAP_SPACING_FT HOOK_SPACING_FT
	,HOOKS_TRAPS_PER_SKATE HOOKS_PER_SKATE
	,MC.BEST_DEPTH AS BEST_DEPTH_M
	,MC.SPECIES_CODE
	,ISNULL(LANDED_KG, 0) AS LANDED_KG
	,ISNULL(DISCARDED_KG, 0) AS DISCARDED_KG
FROM GFFOS.dbo.GF_MERGED_CATCH MC
	LEFT JOIN GFFOS.dbo.LOCALITY L ON MC.LOCALITY_CODE = L.LOCALITY_CODE AND MC.MAJOR_STAT_AREA_CODE = L.MAJOR_STAT_AREA_CODE AND MC.MINOR_STAT_AREA_CODE = L.MINOR_STAT_AREA_CODE
	LEFT JOIN GFFOS.dbo.GF_FE_LONGLINE_GEAR_SPECS LLSP ON CAST(MC.FISHING_EVENT_ID AS BIGINT) = LLSP.FISHING_EVENT_ID
WHERE
	MC.MAJOR_STAT_AREA_CODE IN ('03', '04', '05','06','07','08','09')
		AND MC.GEAR IN ('HOOK AND LINE')
		AND FISHERY_SECTOR IN ('ZN', 'ROCKFISH OUTSIDE', 'HALIBUT', 'HALIBUT AND SABLEFISH', 'SABLEFISH')

	-- insert species here

	SELECT BEST_DATE,
	VESSEL_NAME,
	VESSEL_REGISTRATION_NUMBER,
	FISHERY_SECTOR,
	TRIP_ID,
	FISHING_EVENT_ID,
	FE_START_DATE,
	FE_END_DATE,
	SPECIES_CODE,
	GEAR,
	BEST_DEPTH,
	MAJOR_STAT_AREA_CODE,
	MINOR_STAT_AREA_CODE,
	LOCALITY_CODE,
	LATITUDE,
	LONGITUDE,
	ISNULL(LANDED_KG, 0) AS LANDED_KG,
	ISNULL(DISCARDED_KG, 0) AS DISCARDED_KG
FROM GFFOS.dbo.GF_MERGED_CATCH C
	WHERE FE_END_DATE > FE_START_DATE AND 

-- insert filters here


