SELECT SS.SURVEY_SERIES_ID, 
	SSS.SURVEY_SERIES_NAME, 
	SS.BLOCK_DESIGNATION, 
	SS.LATITUDE, 
	SS.LONGITUDE
FROM 
SURVEY_SITE SS
INNER JOIN SURVEY_SERIES SSS
	ON SS.SURVEY_SERIES_ID=SSS.SURVEY_SERIES_ID

WHERE SS.SURVEY_SERIES_ID in (1, 3, 4, 16, 39, 40)
-- insert ssid here
	AND SS.SELECTION_IND = 1 /*this line selects only the currently active blocks*/
