SELECT
FEC.TRIP_ID,
FE.FE_PARENT_EVENT_ID,
FE.FE_MAJOR_LEVEL_ID,
FE.FE_SUB_LEVEL_ID,
C.SPECIES_CODE,
SUM(CATCH_COUNT) AS CATCH_COUNT
FROM FISHING_EVENT_CATCH FEC
INNER JOIN FISHING_EVENT FE ON FE.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
INNER JOIN CATCH C ON C.CATCH_ID = FEC.CATCH_ID
INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = FEC.TRIP_ID
GROUP BY FEC.TRIP_ID,
---FEC.FISHING_EVENT_ID,
FE.FE_PARENT_EVENT_ID,
FE.FE_MAJOR_LEVEL_ID,
FE.FE_SUB_LEVEL_ID,
C.SPECIES_CODE
ORDER BY FEC.TRIP_ID, FE.FE_MAJOR_LEVEL_ID
