/*
Set-based equivalent of proc_catmat_2011 for vectors of species and survey
series IDs. Inject both filters before executing:

  inject_filter("AND SP.SPECIES_CODE IN", species, sql_code = sql)
  ssid_marker <- paste("-- insert", "ssid here")
  inject_filter("AND S.SURVEY_SERIES_ID IN", ssid, sql_code = sql,
    search_flag = ssid_marker, conversion_func = I)

The legacy procedure used @use_mouthwidth = 0 by default. This query preserves
that default and therefore uses doorspread rather than mouth opening width.

Important: grouping is selected through FISHING_EVENT_GROUPING and validated
against SURVEY_GROUPING for the particular survey. It is intentionally not
required to equal FISHING_EVENT.GROUPING_CODE. This reproduces legacy
re-stratification such as WCHG 2006 (old codes 125--129, valid codes 151--154).
*/

SET NOCOUNT ON;

/* Materialize the requested species once. */
SELECT DISTINCT SP.SPECIES_CODE
INTO #REQUESTED_SPECIES
FROM SPECIES SP
WHERE SP.SPECIES_CODE IS NOT NULL
  -- insert species here
;

CREATE UNIQUE CLUSTERED INDEX IX_REQUESTED_SPECIES
  ON #REQUESTED_SPECIES (SPECIES_CODE);

/* Build every selected survey set once, independent of species. */
SELECT
  S.SURVEY_SERIES_ID,
  S.SURVEY_ID,
  S.SURVEY_DESC,
  TRS.TRIP_ID,
  YEAR(T.TRIP_START_DATE) AS [YEAR],
  FE.FISHING_EVENT_ID,
  FE.FE_MAJOR_LEVEL_ID,
  FE.FE_START_LATTITUDE_DEGREE + FE.FE_START_LATTITUDE_MINUTE / 60.0 AS LATITUDE,
  -(FE.FE_START_LONGITUDE_DEGREE + FE.FE_START_LONGITUDE_MINUTE / 60.0) AS LONGITUDE,
  FEG.GROUPING_CODE,
  FE.MAJOR_STAT_AREA_CODE,
  FE.MINOR_STAT_AREA_CODE,
  FE.FE_BEGINNING_BOTTOM_DEPTH AS DEPTH_M,
  ISNULL(
    DATEDIFF(MINUTE, FE.FE_BEGIN_BOTTOM_CONTACT_TIME, FE.FE_END_BOTTOM_CONTACT_TIME),
    DATEDIFF(MINUTE, FE.FE_END_DEPLOYMENT_TIME, FE.FE_BEGIN_RETRIEVAL_TIME)
  ) AS DURATION_MIN,
  NULLIF(FE.FE_DISTANCE_TRAVELLED, 0) * 1000.0 AS TOW_LENGTH_M,
  ISNULL(NULLIF(TSP.TRLSP_DOORSPREAD, 0), ISNULL(BD.DOORSPREAD, 0)) AS DOORSPREAD_M,
  ISNULL(
    NULLIF(TSP.TRLSP_SPEED, 0) * 16.66667,
    ISNULL(BD.SPEED, 0) * 16.66667
  ) AS SPEED_MPM
INTO #SETS
FROM SURVEY S
INNER JOIN TRIP_SURVEY TRS
  ON TRS.SURVEY_ID = S.SURVEY_ID
INNER JOIN TRIP T
  ON T.TRIP_ID = TRS.TRIP_ID
INNER JOIN FISHING_EVENT FE
  ON FE.TRIP_ID = T.TRIP_ID
LEFT JOIN TRAWL_SPECS TSP
  ON TSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
INNER JOIN FISHING_EVENT_GROUPING FEG
  ON FEG.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
INNER JOIN SURVEY_GROUPING SG
  ON SG.SURVEY_ID = S.SURVEY_ID
  AND SG.GROUPING_CODE = FEG.GROUPING_CODE
LEFT JOIN BOOT_DEFAULTS BD
  ON BD.SURVEY_ID = S.SURVEY_ID
WHERE ISNULL(TSP.USABILITY_CODE, 1) IN (0, 1, 2, 6)
  AND FE.FE_PARENT_EVENT_ID IS NULL
  -- insert ssid here
;

CREATE CLUSTERED INDEX IX_SETS_EVENT
  ON #SETS (FISHING_EVENT_ID);

/* Avoid multiplying catches if an event appears in more than one set row. */
SELECT DISTINCT FISHING_EVENT_ID
INTO #SET_EVENTS
FROM #SETS;

CREATE UNIQUE CLUSTERED INDEX IX_SET_EVENTS
  ON #SET_EVENTS (FISHING_EVENT_ID);

/* Aggregate catch once for all selected events and requested species. */
SELECT
  FEC.FISHING_EVENT_ID,
  C.SPECIES_CODE,
  CAST(SUM(ISNULL(C.CATCH_WEIGHT, 0)) AS FLOAT) AS CATCH_WEIGHT,
  SUM(ISNULL(C.CATCH_COUNT, 0)) AS CATCH_COUNT
INTO #CATCH
FROM #SET_EVENTS E
INNER JOIN FISHING_EVENT_CATCH FEC
  ON FEC.FISHING_EVENT_ID = E.FISHING_EVENT_ID
INNER JOIN CATCH C
  ON C.CATCH_ID = FEC.CATCH_ID
INNER JOIN #REQUESTED_SPECIES RSP
  ON RSP.SPECIES_CODE = C.SPECIES_CODE
GROUP BY FEC.FISHING_EVENT_ID, C.SPECIES_CODE;

CREATE UNIQUE CLUSTERED INDEX IX_CATCH_EVENT_SPECIES
  ON #CATCH (FISHING_EVENT_ID, SPECIES_CODE);

/* Cross with species last so species-absent sets are retained as zero catches. */
SELECT
  S.SURVEY_SERIES_ID,
  S.SURVEY_ID,
  RSP.SPECIES_CODE,
  S.SURVEY_DESC,
  S.TRIP_ID,
  S.[YEAR],
  S.FISHING_EVENT_ID,
  S.FE_MAJOR_LEVEL_ID,
  S.LATITUDE,
  S.LONGITUDE,
  S.GROUPING_CODE,
  S.MAJOR_STAT_AREA_CODE,
  S.MINOR_STAT_AREA_CODE,
  S.DEPTH_M,
  S.DURATION_MIN,
  S.DOORSPREAD_M,
  S.SPEED_MPM,
  S.TOW_LENGTH_M,
  ISNULL(CA.CATCH_WEIGHT, 0.0) AS CATCH_WEIGHT,
  CAST(
    ISNULL(
      ISNULL(CA.CATCH_WEIGHT, 0.0) /
        NULLIF(S.TOW_LENGTH_M * S.DOORSPREAD_M, 0),
      ISNULL(
        ISNULL(CA.CATCH_WEIGHT, 0.0) /
          NULLIF(S.DOORSPREAD_M * S.SPEED_MPM * S.DURATION_MIN, 0),
        0
      )
    ) AS DECIMAL(20, 15)
  ) AS DENSITY_KGPM2,
  ISNULL(CA.CATCH_COUNT, 0) AS CATCH_COUNT,
  ISNULL(CA.CATCH_COUNT, 0) /
    NULLIF(S.DOORSPREAD_M * S.SPEED_MPM * S.DURATION_MIN, 0) AS DENSITY_PCPM2
FROM #SETS S
CROSS JOIN #REQUESTED_SPECIES RSP
LEFT JOIN #CATCH CA
  ON CA.FISHING_EVENT_ID = S.FISHING_EVENT_ID
  AND CA.SPECIES_CODE = RSP.SPECIES_CODE
ORDER BY
  S.SURVEY_SERIES_ID,
  S.[YEAR],
  S.SURVEY_ID,
  S.FISHING_EVENT_ID,
  RSP.SPECIES_CODE;
