SELECT
    FE.FISHING_EVENT_ID,
    FE.FE_PARENT_EVENT_ID,
    FE.FE_MAJOR_LEVEL_ID,
    FE.FE_SUB_LEVEL_ID,
    FE.FE_MINOR_LEVEL_ID,
    T.TRIP_ID,
    ISNULL(S1.SURVEY_SERIES_ID, S.SURVEY_SERIES_ID) AS SURVEY_SERIES_ID,
    ISNULL(G.SURVEY_SERIES_ID, S.SURVEY_SERIES_ID) AS SURVEY_SERIES_OG,
    ISNULL(S1.SURVEY_ID, S.SURVEY_ID) AS SURVEY_ID,
    A.ACTIVITY_DESC,
    TA.ACTIVITY_CODE,
    R.REASON_DESC,
    YEAR(T.TRIP_START_DATE) AS TRIP_YEAR,
    YEAR(COALESCE (FE_BEGIN_BOTTOM_CONTACT_TIME, FE_END_BOTTOM_CONTACT_TIME, FE_END_DEPLOYMENT_TIME,
      FE_BEGIN_RETRIEVAL_TIME, FE_BEGIN_DEPLOYMENT_TIME, FE_END_RETRIEVAL_TIME, T.TRIP_START_DATE)) AS YEAR,
    MONTH(COALESCE (FE_BEGIN_BOTTOM_CONTACT_TIME, FE_END_BOTTOM_CONTACT_TIME, FE_END_DEPLOYMENT_TIME,
      FE_BEGIN_RETRIEVAL_TIME, FE_BEGIN_DEPLOYMENT_TIME, FE_END_RETRIEVAL_TIME)) AS MONTH,
    DAY(COALESCE (FE_BEGIN_BOTTOM_CONTACT_TIME, FE_END_BOTTOM_CONTACT_TIME, FE_END_DEPLOYMENT_TIME,
      FE_BEGIN_RETRIEVAL_TIME, FE_BEGIN_DEPLOYMENT_TIME, FE_END_RETRIEVAL_TIME)) AS DAY,
    ISNULL(FE_BEGIN_BOTTOM_CONTACT_TIME, FE_END_DEPLOYMENT_TIME) AS TIME_DEPLOYED,
    ISNULL(FE_END_BOTTOM_CONTACT_TIME, FE_BEGIN_RETRIEVAL_TIME) AS TIME_RETRIEVED,
    FE_END_DEPLOYMENT_TIME AS TIME_END_DEPLOYMENT,
    FE_BEGIN_RETRIEVAL_TIME AS TIME_BEGIN_RETRIEVAL,
    FE_START_LATTITUDE_DEGREE + FE_START_LATTITUDE_MINUTE / 60 AS LATITUDE,
    -(FE_START_LONGITUDE_DEGREE + FE_START_LONGITUDE_MINUTE / 60) AS LONGITUDE,
    FE_END_LATTITUDE_DEGREE + FE_END_LATTITUDE_MINUTE / 60 AS LATITUDE_END,
    -(FE_END_LONGITUDE_DEGREE + FE_END_LONGITUDE_MINUTE / 60) AS LONGITUDE_END,
    FE.MAJOR_STAT_AREA_CODE,
    FE.MINOR_STAT_AREA_CODE,
    COALESCE(FE.FE_MODAL_BOTTOM_DEPTH, FE.FE_BEGINNING_BOTTOM_DEPTH, FE.FE_END_BOTTOM_DEPTH,
               FE.FE_MIN_BOTTOM_DEPTH, FE.FE_MAX_BOTTOM_DEPTH) AS DEPTH_M,
    FE.FE_BEGINNING_BOTTOM_DEPTH AS DEPTH_BEGIN,
    FE_END_BOTTOM_DEPTH AS DEPTH_END,
    --- FE.FE_BOTTOM_WATER_TEMPERATURE, --- rarely available
    T.VESSEL_ID AS VESSEL_ID,
    T.CAPTAIN_ID AS CAPTAIN_ID,
    ISNULL(DATEDIFF(MI,FE_BEGIN_BOTTOM_CONTACT_TIME,
      FE_END_BOTTOM_CONTACT_TIME),
         DATEDIFF(MI,FE_END_DEPLOYMENT_TIME,
      FE_BEGIN_RETRIEVAL_TIME)) AS DURATION_MIN,
    NULLIF(FE_DISTANCE_TRAVELLED,0) * 1000.0 AS TOW_LENGTH_M,
    NULLIF(TRSP.TRLSP_MOUTH_OPENING_WIDTH,0) AS MOUTH_WIDTH_M,
    ISNULL(NULLIF(TRSP.TRLSP_DOORSPREAD,0), BD.DOORSPREAD) AS DOORSPREAD_M,
    ISNULL(NULLIF(TRSP.TRLSP_SPEED,0), BD.SPEED)* 16.66667 AS SPEED_MPM,
    CASE WHEN FE.GEAR_CODE IN (5) THEN LLSP.HOOK_CODE
      WHEN FE.GEAR_CODE IN (4) THEN HLSP.HOOK_CODE
      ELSE 0 END AS HOOK_CODE,
    LGLSP_HOOK_COUNT,
    H.HOOK_DESC,
    HSZ.HOOKSIZE_DESC,
    CASE WHEN FE.GEAR_CODE IN (1, 6, 8, 11, 14, 16) THEN ISNULL(TRSP.USABILITY_CODE, 0)
      WHEN FE.GEAR_CODE IN (2) THEN ISNULL(TPSP.USABILITY_CODE, 0)
      WHEN FE.GEAR_CODE IN (5) THEN ISNULL(LLSP.USABILITY_CODE, 0)
      WHEN FE.GEAR_CODE IN (4) THEN ISNULL(HLSP.USABILITY_CODE, 0)
      ELSE 0 END AS USABILITY_CODE,
    FE.GROUPING_CODE AS GROUPING_CODE_ORIGINAL,
    G.GROUPING_DESC AS GROUPING_DESC_ORIGINAL,
    FEG.GROUPING_CODE AS GROUPING_CODE_UPDATED, -- for updated survey definitions
    G2.GROUPING_DESC AS GROUPING_DESC_UPDATED,
    G.GROUPING_DEPTH_ID,
    S.ORIGINAL_IND
    FROM FISHING_EVENT FE
      LEFT JOIN TRAWL_SPECS TRSP ON TRSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
      LEFT JOIN LONGLINE_SPECS LLSP ON LLSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
      LEFT JOIN TRAP_SPECS TPSP ON TPSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
      LEFT JOIN HANDLINE_SPECS HLSP ON HLSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
      LEFT JOIN TRIP T ON T.TRIP_ID = FE.TRIP_ID
      LEFT JOIN TRIP_ACTIVITY TA ON TA.TRIP_ID = FE.TRIP_ID
      LEFT JOIN ACTIVITY A ON A.ACTIVITY_CODE = TA.ACTIVITY_CODE
      LEFT JOIN TRIP_SURVEY TRS ON TRS.TRIP_ID = T.TRIP_ID
      LEFT JOIN REASON R ON FE.REASON_CODE = R.REASON_CODE
      LEFT JOIN HOOK H ON H.HOOK_CODE = LLSP.HOOK_CODE
      LEFT JOIN HOOKSIZE HSZ ON HSZ.HOOKSIZE_CODE = LLSP.HOOKSIZE_CODE
      LEFT JOIN GROUPING G ON G.GROUPING_CODE = FE.GROUPING_CODE
      LEFT JOIN SURVEY S1 ON S1.SURVEY_ID = TRS.SURVEY_ID --AND S1.SURVEY_SERIES_ID = G.SURVEY_SERIES_ID
      LEFT JOIN SURVEY_GROUPING SG ON SG.SURVEY_ID = S1.SURVEY_ID AND SG.GROUPING_CODE = FE.GROUPING_CODE
      LEFT JOIN FISHING_EVENT_GROUPING FEG ON FEG.FISHING_EVENT_ID = FE.FISHING_EVENT_ID AND SG.GROUPING_CODE = FEG.GROUPING_CODE
      LEFT JOIN GROUPING G2 ON G2.GROUPING_CODE = FEG.GROUPING_CODE
      LEFT JOIN SURVEY S ON S.SURVEY_ID = TRS.SURVEY_ID
      LEFT JOIN BOOT_DEFAULTS BD ON BD.SURVEY_ID = ISNULL(S1.SURVEY_ID, S.SURVEY_ID)
    WHERE FE.FISHING_EVENT_ID IS NOT NULL
      -- insert ssid here
      -- insert fe_vector here
      -- insert major here
    ORDER BY A.ACTIVITY_DESC, T.TRIP_START_DATE, FE.FISHING_EVENT_ID
