SELECT
  DATABASE_NAME
  ,YEAR(BEST_DATE) YEAR
  ,FISHERY_SECTOR
  ,MC.TRIP_ID
  ,MC.FISHING_EVENT_ID
  ,MC.MAJOR_STAT_AREA_CODE
  ,MSA.MAJOR_STAT_AREA_NAME
  ,GEAR
  ,BEST_DEPTH
  ,MC.SPECIES_CODE
  ,SPECIES_COMMON_NAME
  --,COALESCE(NULLIF(MC.LANDED_KG,0), NULLIF(MC.LANDED_PCS*MNWT,0), 0) AS landed
  ,MC.LANDED_KG
 --,COALESCE(NULLIF(MC.DISCARDED_KG,0), NULLIF(MC.DISCARDED_PCS*FW.MNWT,0), 0) AS discard
  ,MC.DISCARDED_KG
  ,MC.LANDED_PCS
  ,DISCARDED_PCS
FROM GFFOS.dbo.GF_MERGED_CATCH MC
	INNER JOIN GFFOS.dbo.SPECIES SP ON SP.SPECIES_CODE = MC.SPECIES_CODE
	INNER JOIN GFBioSQL.dbo.MAJOR_STAT_AREA MSA ON MC.MAJOR_STAT_AREA_CODE = MSA.MAJOR_STAT_AREA_CODE
-- insert species here
ORDER BY YEAR, FISHERY_SECTOR, TRIP_ID, FISHING_EVENT_ID
