SELECT SS.SURVEY_SERIES_ID,
	SSS.SURVEY_SERIES_NAME,
	SS.BLOCK_DESIGNATION,
	SS.GROUPING_CODE,
	SS.GROUPING_DESC,
	GEOM.STPointN(1).Lat AS PT1_LAT,
	GEOM.STPointN(1).Long AS PT1_LON,
	GEOM.STPointN(2).Lat AS PT2_LAT,
	GEOM.STPointN(2).Long AS PT2_LON,
	GEOM.STPointN(3).Lat AS PT3_LAT,
	GEOM.STPointN(3).Long AS PT3_LON,
	GEOM.STPointN(4).Lat AS PT4_LAT,
	GEOM.STPointN(4).Long AS PT4_LON,
	SS.DEPTH_M AS SURVEY_SITE_DEPTH_M,
	SS.LATITUDE,
	SS.LONGITUDE,
	SS.SELECTION_IND
FROM
SURVEY_SITE SS
INNER JOIN SURVEY_SERIES SSS
	ON SS.SURVEY_SERIES_ID=SSS.SURVEY_SERIES_ID
WHERE SS.SURVEY_SERIES_ID in ( 1, 2, 3, 4, 7, 14, 16, 22, 36, 39, 40)
-- insert ssid here
-- AND SS.SELECTION_IND = 1 /*this line selects only the currently active blocks*/
