SELECT BEST_DATE
	,VESSEL_NAME
	,VESSEL_REGISTRATION_NUMBER
	,FISHERY_SECTOR
	,TRIP_ID
	,FISHING_EVENT_ID
	,FE_START_DATE
	,FE_END_DATE
	,S.SPECIES_CODE
	,SPECIES_COMMON_NAME
	,GEAR
	,BEST_DEPTH
	,MAJOR_STAT_AREA_CODE
	,MINOR_STAT_AREA_CODE
	,LOCALITY_CODE
	,LATITUDE
	,LONGITUDE
	,ISNULL(LANDED_KG, 0) AS LANDED_KG
	,ISNULL(DISCARDED_KG, 0) AS DISCARDED_KG
	,ISNULL(LANDED_KG, 0) + ISNULL(DISCARDED_KG, 0) CATCH_KG
FROM GFFOS.dbo.GF_MERGED_CATCH C
INNER JOIN GFFOS.dbo.SPECIES S ON S.SPECIES_CODE = C.SPECIES_CODE
-- insert filters here

