/*
Set-based equivalent of proc_catmat_ll_2013 for vectors of species and survey
series IDs. Inject both filters before executing:

  inject_filter("AND SP.SPECIES_CODE IN", species, sql_code = sql)
  ssid_marker <- paste("-- insert", "ssid here")
  inject_filter("AND S.SURVEY_SERIES_ID IN", ssid, sql_code = sql,
    search_flag = ssid_marker, conversion_func = I)

The parent -> skate -> hook hierarchy, grouping source, usability filtering,
area-swept constants, and zero-catch cross-product match proc_catmat_ll_2013.
*/

SET NOCOUNT ON;

/* Materialize the requested species once. */
SELECT DISTINCT SP.SPECIES_CODE
INTO #REQUESTED_SPECIES
FROM SPECIES SP
WHERE SP.SPECIES_CODE IS NOT NULL
  -- insert species here
;

CREATE UNIQUE CLUSTERED INDEX IX_REQUESTED_SPECIES
  ON #REQUESTED_SPECIES (SPECIES_CODE);

/* Skate-level events: A in proc_catmat_ll_2013. */
SELECT
  S.SURVEY_SERIES_ID,
  TRS.SURVEY_ID,
  FE.FE_PARENT_EVENT_ID AS PARENT_EVENT_ID,
  FE.FISHING_EVENT_ID AS SKATE_EVENT_ID
INTO #SKATES
FROM SURVEY S
INNER JOIN TRIP_SURVEY TRS
  ON TRS.SURVEY_ID = S.SURVEY_ID
INNER JOIN FISHING_EVENT FE
  ON FE.TRIP_ID = TRS.TRIP_ID
WHERE FE.FE_MINOR_LEVEL_ID IS NULL
  AND FE.FE_PARENT_EVENT_ID IS NOT NULL
  -- insert ssid here
;

CREATE CLUSTERED INDEX IX_SKATES
  ON #SKATES (SURVEY_ID, SKATE_EVENT_ID, PARENT_EVENT_ID);

/* Hook-level children per skate: B in proc_catmat_ll_2013. */
SELECT
  TRS.SURVEY_ID,
  FE.FE_PARENT_EVENT_ID AS SKATE_EVENT_ID,
  COUNT(FE.FISHING_EVENT_ID) AS NHOOKS
INTO #HOOKS
FROM SURVEY S
INNER JOIN TRIP_SURVEY TRS
  ON TRS.SURVEY_ID = S.SURVEY_ID
INNER JOIN FISHING_EVENT FE
  ON FE.TRIP_ID = TRS.TRIP_ID
WHERE FE.FE_MINOR_LEVEL_ID IS NOT NULL
  -- insert ssid here
GROUP BY TRS.SURVEY_ID, FE.FE_PARENT_EVENT_ID;

CREATE UNIQUE CLUSTERED INDEX IX_HOOKS
  ON #HOOKS (SURVEY_ID, SKATE_EVENT_ID);

/* Usable parent-set attributes: FE in proc_catmat_ll_2013. */
SELECT
  S.SURVEY_SERIES_ID,
  S.SURVEY_ID,
  S.SURVEY_DESC,
  FE.FISHING_EVENT_ID,
  FE.GROUPING_CODE,
  YEAR(T.TRIP_START_DATE) AS [YEAR]
INTO #PARENTS
FROM SURVEY S
INNER JOIN TRIP_SURVEY TRS
  ON TRS.SURVEY_ID = S.SURVEY_ID
INNER JOIN TRIP T
  ON T.TRIP_ID = TRS.TRIP_ID
INNER JOIN FISHING_EVENT FE
  ON FE.TRIP_ID = T.TRIP_ID
INNER JOIN LONGLINE_SPECS LSP
  ON LSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
INNER JOIN GROUPING G
  ON G.GROUPING_CODE = FE.GROUPING_CODE
WHERE ISNULL(LSP.USABILITY_CODE, 1) IN (0, 1, 2, 6)
  -- insert ssid here
;

CREATE CLUSTERED INDEX IX_PARENTS
  ON #PARENTS (SURVEY_ID, FISHING_EVENT_ID);

/* Build every selected longline set once, independent of species. */
SELECT
  MAX(P.SURVEY_DESC) AS SURVEY_DESC,
  MAX(P.SURVEY_SERIES_ID) AS SURVEY_SERIES_ID,
  SK.SURVEY_ID,
  MAX(P.[YEAR]) AS [YEAR],
  SK.PARENT_EVENT_ID AS FISHING_EVENT_ID,
  MAX(P.GROUPING_CODE) AS GROUPING_CODE,
  COUNT(SK.SKATE_EVENT_ID) AS SKATE_COUNT,
  SUM(H.NHOOKS) AS HOOK_COUNT,
  CASE MAX(P.SURVEY_SERIES_ID)
    WHEN 14 THEN 0.0054864
    ELSE 0.0024384
  END * 0.009144 * SUM(H.NHOOKS) AS AREA_SWEPT_KM2
INTO #SETS
FROM #SKATES SK
INNER JOIN #HOOKS H
  ON H.SURVEY_ID = SK.SURVEY_ID
  AND H.SKATE_EVENT_ID = SK.SKATE_EVENT_ID
INNER JOIN #PARENTS P
  ON P.SURVEY_ID = SK.SURVEY_ID
  AND P.FISHING_EVENT_ID = SK.PARENT_EVENT_ID
GROUP BY SK.SURVEY_ID, SK.PARENT_EVENT_ID;

CREATE CLUSTERED INDEX IX_SETS_EVENT
  ON #SETS (FISHING_EVENT_ID);

SELECT DISTINCT FISHING_EVENT_ID
INTO #SET_EVENTS
FROM #SETS;

CREATE UNIQUE CLUSTERED INDEX IX_SET_EVENTS
  ON #SET_EVENTS (FISHING_EVENT_ID);

/* Aggregate catch once for all selected parent events and species. */
SELECT
  FEC.FISHING_EVENT_ID,
  C.SPECIES_CODE,
  SUM(ISNULL(C.CATCH_WEIGHT, 0)) AS CATCH_WEIGHT,
  SUM(ISNULL(C.CATCH_COUNT, 0)) AS CATCH_COUNT
INTO #CATCH
FROM #SET_EVENTS E
INNER JOIN FISHING_EVENT_CATCH FEC
  ON FEC.FISHING_EVENT_ID = E.FISHING_EVENT_ID
INNER JOIN CATCH C
  ON C.CATCH_ID = FEC.CATCH_ID
INNER JOIN #REQUESTED_SPECIES RSP
  ON RSP.SPECIES_CODE = C.SPECIES_CODE
GROUP BY FEC.FISHING_EVENT_ID, C.SPECIES_CODE;

CREATE UNIQUE CLUSTERED INDEX IX_CATCH_EVENT_SPECIES
  ON #CATCH (FISHING_EVENT_ID, SPECIES_CODE);

/* Cross with species last so species-absent sets are retained as zero catches. */
SELECT
  S.SURVEY_DESC,
  S.SURVEY_SERIES_ID,
  S.SURVEY_ID,
  S.[YEAR],
  RSP.SPECIES_CODE,
  S.FISHING_EVENT_ID,
  S.GROUPING_CODE,
  S.SKATE_COUNT,
  S.HOOK_COUNT,
  ISNULL(CA.CATCH_WEIGHT, 0) AS CATCH_WEIGHT,
  ISNULL(CA.CATCH_COUNT, 0) AS CATCH_COUNT,
  ISNULL(CA.CATCH_COUNT, 0) / NULLIF(S.AREA_SWEPT_KM2, 0) AS DENSITY_PPKM2
FROM #SETS S
CROSS JOIN #REQUESTED_SPECIES RSP
LEFT JOIN #CATCH CA
  ON CA.FISHING_EVENT_ID = S.FISHING_EVENT_ID
  AND CA.SPECIES_CODE = RSP.SPECIES_CODE
ORDER BY
  S.SURVEY_SERIES_ID,
  S.[YEAR],
  S.SURVEY_ID,
  S.FISHING_EVENT_ID,
  RSP.SPECIES_CODE;
