SELECT SM.SAMPLE_ID
	,SP.SPECIMEN_ID
	,SC.COLLECTED_ATTRIBUTE_CODE
	,COLLECTED_ATTRIBUTE_DESC
	,SE.EXISTENCE_ATTRIBUTE_CODE
	,EXISTENCE_ATTRIBUTE_DESC
	,STORAGE_CONTAINER_TYPE_CODE
	,STORAGE_CONTAINER_ID
	,STORAGE_CONTAINER_SUB_ID
      ,SS.SPECIES_CODE PREY_SPECIES
      ,PREY_VOLUME
      ,DIGESTION_STATE_CODE
FROM B21_Samples SM
	INNER JOIN B22_Specimens SP ON SP.SAMPLE_ID = SM.SAMPLE_ID
	INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = SM.TRIP_ID
	INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
	LEFT JOIN SPECIMEN_COLLECTED SC ON SC.SPECIMEN_ID = SP.SPECIMEN_ID AND SC.SAMPLE_ID = SM.SAMPLE_ID AND SC.SAMPLE_ID = SP.SAMPLE_ID
	LEFT JOIN COLLECTED_ATTRIBUTE CA ON CA.COLLECTED_ATTRIBUTE_CODE = SC.COLLECTED_ATTRIBUTE_CODE
	LEFT JOIN SPECIMEN_EXISTENCE SE ON SE.SAMPLE_ID = SM.SAMPLE_ID AND SE.SAMPLE_ID = SP.SAMPLE_ID AND SE.SPECIMEN_ID = SP.SPECIMEN_ID AND SE.SPECIMEN_ID = SC.SPECIMEN_ID
	LEFT JOIN EXISTENCE_ATTRIBUTE EA ON EA.EXISTENCE_ATTRIBUTE_CODE = SE.EXISTENCE_ATTRIBUTE_CODE
	LEFT JOIN SPECIMEN_STOMACH SS ON SS.SPECIMEN_ID = SP.SPECIMEN_ID
WHERE SURVEY_SERIES_ID IN (80, 88) 
ORDER BY PREY_VOLUME

