SELECT YEAR(trp.TRIP_START_DATE) AS year,
  trp.TRIP_ID,
  fe.FISHING_EVENT_ID,
  fe.FE_MAJOR_LEVEL_ID,
  fe.FE_BEGIN_DEPLOYMENT_TIME,
  fe.FE_BEGIN_RETRIEVAL_TIME,
  c.SPECIES_CODE,
  GFBioSQL.dbo.SPECIES.SPECIES_COMMON_NAME,
  GFBioSQL.dbo.SPECIES.SPECIES_SCIENCE_NAME,
  c.CATCH_WEIGHT,
  c.CATCH_COUNT,
  LEFT(maj.MAJOR_STAT_AREA_NAME, 2) AS major,
  fe.FE_FISHING_GROUND_COMMENT,
  GFBioSQL.dbo.CATCH_VERIFICATION.CATCH_VERIFICATION_DESC,
  reas.REASON_DESC
FROM   GFBioSQL.dbo.TRIP AS trp INNER JOIN
  GFBioSQL.dbo.FISHING_EVENT AS fe ON trp.TRIP_ID = fe.TRIP_ID INNER JOIN
  GFBioSQL.dbo.FISHING_EVENT_CATCH AS fec ON fe.FISHING_EVENT_ID = fec.FISHING_EVENT_ID INNER JOIN
  GFBioSQL.dbo.CATCH AS c ON fec.CATCH_ID = c.CATCH_ID INNER JOIN
  GFBioSQL.dbo.TRIP_ACTIVITY AS act ON trp.TRIP_ID = act.TRIP_ID INNER JOIN
  GFBioSQL.dbo.SPECIES ON c.SPECIES_CODE = GFBioSQL.dbo.SPECIES.SPECIES_CODE LEFT OUTER JOIN
  GFBioSQL.dbo.CATCH_VERIFICATION ON c.CATCH_VERIFICATION_CODE = GFBioSQL.dbo.CATCH_VERIFICATION.CATCH_VERIFICATION_CODE LEFT OUTER JOIN
  GFBioSQL.dbo.C_Reason AS reas ON fe.REASON_CODE = reas.REASON_CODE LEFT OUTER JOIN
  GFBioSQL.dbo.MAJOR_STAT_AREA AS maj ON fe.MAJOR_STAT_AREA_CODE = maj.MAJOR_STAT_AREA_CODE
WHERE   (fe.FE_SUB_LEVEL_ID IS NULL)
GROUP BY YEAR(trp.TRIP_START_DATE),
  trp.TRIP_ID,
  c.CATCH_WEIGHT,
  c.CATCH_COUNT,
  fe.FISHING_EVENT_ID,
  fe.FE_MAJOR_LEVEL_ID,
  act.ACTIVITY_CODE,
  c.SPECIES_CODE,
LEFT(maj.MAJOR_STAT_AREA_NAME, 2),
  fe.FE_FISHING_GROUND_COMMENT,
  fe.FE_BEGIN_DEPLOYMENT_TIME,
  GFBioSQL.dbo.CATCH_VERIFICATION.CATCH_VERIFICATION_DESC,
  fe.FE_BEGIN_RETRIEVAL_TIME,
  reas.REASON_DESC,
  GFBioSQL.dbo.SPECIES.SPECIES_COMMON_NAME,
  GFBioSQL.dbo.SPECIES.SPECIES_SCIENCE_NAME
HAVING   (act.ACTIVITY_CODE = 19)
ORDER BY year DESC, trp.TRIP_ID, fe.FE_MAJOR_LEVEL_ID
