
-- COUNT HOW MANY REX FE'S CAUGHT EACH OF THE SPECIES IN THEIR TOP 10
-- OR SUM OF LANDED_KG FOR SHORTRAKER TRIPS WHERE A SPECIES WAS IN THE TOP 10 CAUGHT
SELECT C.SPECIES_CODE
	,SPECIES_COMMON_NAME
	,COUNT(DISTINCT FISHING_EVENT_ID) COUNT_FISHING_EVENTS
	,SUM(LANDED_KG) TOTAL_LANDED_KG
	,COUNT(DISTINCT(YEAR)) NUM_YEARS
	
FROM(

	-- Select top 5 or 10 species caught in each trip with shortraker
	SELECT YEAR, TRIP_ID, FISHING_EVENT_ID, SPECIES_CODE, LANDED_KG, RANK
	FROM (

		-- Rank each species by landed_kg for each trip which caugth shortraker
		SELECT YEAR(BEST_DATE) YEAR, MC.TRIP_ID, MC.FISHING_EVENT_ID, SPECIES_CODE, LANDED_KG, ROW_NUMBER() 
			OVER (Partition BY MC.TRIP_ID, MC.FISHING_EVENT_ID
				ORDER BY LANDED_KG DESC) AS RANK
		FROM GF_MERGED_CATCH MC
			RIGHT JOIN

			-- FE's which caught TARGET SPECIES
				(SELECT TRIP_ID, FISHING_EVENT_ID
				FROM GF_MERGED_CATCH MC
				-- insert species here
					AND YEAR(BEST_DATE) > 2007 AND FISHING_EVENT_ID <> 0
					-- insert fishery here
					-- insert gear here
					AND LANDED_KG > 100
				GROUP BY TRIP_ID, FISHING_EVENT_ID) A ON A.FISHING_EVENT_ID = MC.FISHING_EVENT_ID AND A.TRIP_ID = MC.TRIP_ID
		
		WHERE LANDED_KG > 0	
		) B

	WHERE RANK <=10
	) C
		INNER JOIN SPECIES S ON S.SPECIES_CODE = C.SPECIES_CODE
GROUP BY 
	C.SPECIES_CODE
	,SPECIES_COMMON_NAME
ORDER BY COUNT_FISHING_EVENTS DESC, TOTAL_LANDED_KG DESC
