SELECT MC.DATABASE_NAME
	,FISHERY_SECTOR
	,YEAR(MC.BEST_DATE) YEAR
	,MONTH(MC.BEST_DATE) MONTH
	,MC.BEST_DATE
	,MC.TRIP_ID
	,MC.FISHING_EVENT_ID
	,MC.MAJOR_STAT_AREA_CODE MAJ_CDE
	--,MSA.MAJOR_STAT_AREA_DESCRIPTION MAJ_DESC
	,MC.MINOR_STAT_AREA_CODE MIN_CDE
	,MC.LOCALITY_CODE LOC_CDE
	--,L.LOCALITY_DESCRIPTION LOC_DESC
	,LATITUDE LAT
	,LONGITUDE LON
	,MC.GEAR
	,LONGLINE_GEAR_TYPE_NAME GEAR_TYPE
	,NUMBER_GEAR_SET HOOKS_SET
	,NUMBER_GEAR_LOST HOOKS_LOST
	,SKATE_LENGTH_FT
	,HOOK_TRAP_SPACING_FT HOOK_SPACING_FT
	,HOOKS_TRAPS_PER_SKATE HOOKS_PER_SKATE
	,MC.BEST_DEPTH AS BEST_DEPTH_M
	,MC.SPECIES_CODE
	--,SPECIES_COMMON_NAME
	,COALESCE(MC.LANDED_KG,0) AS LANDED_KG
	,COALESCE(MC.DISCARDED_KG,0) AS DISCARDED_KG
	,COALESCE(MC.LANDED_KG,0)+COALESCE(MC.DISCARDED_KG,0) AS TOTCATCH_KG
	,MC.VESSEL_REGISTRATION_NUMBER VESSEL
FROM GFFOS.dbo.GF_MERGED_CATCH MC
	--INNER JOIN GFFOS.dbo.MAJOR_STAT_AREA MSA ON MC.MAJOR_STAT_AREA_CODE = MSA.MAJOR_STAT_AREA_CODE
	--LEFT JOIN GFFOS.dbo.LOCALITY L ON MC.LOCALITY_CODE = L.LOCALITY_CODE AND MC.MAJOR_STAT_AREA_CODE = L.MAJOR_STAT_AREA_CODE AND MC.MINOR_STAT_AREA_CODE = L.MINOR_STAT_AREA_CODE
	LEFT JOIN GFFOS.dbo.GF_FE_LONGLINE_GEAR_SPECS LLSP ON CAST(MC.FISHING_EVENT_ID AS BIGINT) = LLSP.FISHING_EVENT_ID
	LEFT JOIN GFFOS.dbo.LONGLINE_GEAR_TYPE LLGT ON LLGT.LONGLINE_GEAR_TYPE_CODE = LLSP.LONGLINE_GEAR_TYPE_CODE
	--INNER JOIN GFFOS.dbo.SPECIES S ON S.SPECIES_CODE = MC.SPECIES_CODE
WHERE
	MC.MAJOR_STAT_AREA_CODE IN ('03', '04', '05','06','07','08','09')
		AND MC.GEAR IN ('HOOK AND LINE') 

	-- insert species here

