SELECT
SURVEY_SERIES_ID,
ACTIVITY_CODE
FROM GFBioSQL.dbo.SURVEY S
  INNER JOIN GFBioSQL.dbo.TRIP_SURVEY TS ON TS.SURVEY_ID = S.SURVEY_ID
  INNER JOIN GFBioSQL.dbo.TRIP_ACTIVITY TA ON TA.TRIP_ID = TS.TRIP_ID
