SELECT SM.TRIP_ID
	,FISHING_EVENT_ID
	,BLOCK_DESIGNATION
FROM GFBioSQL.dbo.B21_Samples SM
	INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = SM.TRIP_ID
	INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
WHERE BLOCK_DESIGNATION IS NOT NULL
-- insert ssid here
ORDER BY SM.TRIP_ID, FISHING_EVENT_ID
