   SELECT S.SURVEY_SERIES_ID,
      S.SURVEY_ID,
      TRS.TRIP_ID,
      YEAR(T.TRIP_START_DATE) AS TRIP_YEAR,
      YEAR(COALESCE (FE_BEGIN_BOTTOM_CONTACT_TIME, FE_END_BOTTOM_CONTACT_TIME, FE_END_DEPLOYMENT_TIME,
         FE_BEGIN_RETRIEVAL_TIME, FE_BEGIN_DEPLOYMENT_TIME, FE_END_RETRIEVAL_TIME, T.TRIP_START_DATE)) AS YEAR,
      FE.FISHING_EVENT_ID,
      FE.FE_MAJOR_LEVEL_ID,
      FE.FE_START_LATTITUDE_DEGREE + FE.FE_START_LATTITUDE_MINUTE / 60 AS LATITUDE,
      -(FE.FE_START_LONGITUDE_DEGREE + FE.FE_START_LONGITUDE_MINUTE / 60) AS LONGITUDE,
      C.SPECIES_CODE,
      SP.SPECIES_COMMON_NAME,
      SP.SPECIES_SCIENCE_NAME,
      SUM(ISNULL(CATCH_WEIGHT,0)) AS CATCH_WEIGHT,
      SUM(ISNULL(CATCH_COUNT,0)) AS CATCH_COUNT
   FROM SURVEY S
      INNER JOIN TRIP_SURVEY TRS ON
      S.SURVEY_ID = TRS.SURVEY_ID
      INNER JOIN TRIP T ON
      TRS.TRIP_ID = T.TRIP_ID
      INNER JOIN FISHING_EVENT FE ON
      T.TRIP_ID = FE.TRIP_ID
      INNER JOIN FISHING_EVENT_CATCH FEC ON
      S.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
      INNER JOIN CATCH C ON
      FEC.CATCH_ID = C.CATCH_ID
      INNER JOIN SPECIES SP ON SP.SPECIES_CODE = C.SPECIES_CODE
   WHERE FE.FE_PARENT_EVENT_ID IS NULL AND
   -- insert species here
   -- insert ssid here
