--SELECT COUNT(DISTINCT(FISHING_EVENT_ID))
--FROM(
SELECT LLGS.FISHING_EVENT_ID
	,NUMBER_GEAR_SET skates_set
	,NUMBER_GEAR_LOST skates_lost
	,NUMBER_GEAR_SET - ISNULL(NUMBER_GEAR_LOST, 0) skates_obs
	,HOOKS_TRAPS_PER_SKATE hooks_per_skate
	,(NUMBER_GEAR_SET - ISNULL(NUMBER_GEAR_LOST, 0)) * CAST(HOOKS_TRAPS_PER_SKATE AS BIGINT) skates_obs_x_hooks_per_skate
	,HOOK_TRAP_SPACING_FT hooks_per_ft
	,SKATE_LENGTH_FT skate_ft
	,(CAST(SKATE_LENGTH_FT AS BIGINT) * (NUMBER_GEAR_SET - NUMBER_GEAR_LOST))/HOOK_TRAP_SPACING_FT  'skate_ft_x_skates_obs_/_hooks_per_ft'

FROM GFFOS.dbo.GF_FE_LONGLINE_GEAR_SPECS LLGS
	LEFT JOIN GFFOS.dbo.GF_MERGED_CATCH C ON LLGS.FISHING_EVENT_ID = C.FISHING_EVENT_ID
GROUP BY LLGS.FISHING_EVENT_ID
	,NUMBER_GEAR_SET 
	,NUMBER_GEAR_LOST 
	,HOOKS_TRAPS_PER_SKATE 
	,HOOK_TRAP_SPACING_FT 
	,SKATE_LENGTH_FT 
	ORDER BY skates_obs_x_hooks_per_skate DESC, 'skate_ft_x_skates_obs_/_hooks_per_ft' DESC
--	) A
--WHERE skates_obs_x_hooks_per_skate IS NULL AND 'skate_ft_x_skates_obs_/_hooks_per_ft' IS NULL
	