USE [GFBioSQL]
GO

/****** Object:  StoredProcedure [dbo].[proc_catmat_ll_2013]    Script Date: 11/21/2017 12:02:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[proc_catmat_ll_2013] @sid INTEGER, @spp VARCHAR(3)
AS
   SET NOCOUNT ON

      -- Fishing event attributes for good (USABILITY_CODE = 0,1,2,6) sets:
      SELECT A.FE_PARENT_EVENT_ID AS FISHING_EVENT_ID,
         COUNT(A.FISHING_EVENT_ID) AS SKATE_COUNT,
         SUM(B.NHOOKS) AS HOOK_COUNT,
         CASE MAX(SURVEY_SERIES_ID) WHEN 14 THEN 0.0054864 ELSE 0.0024384 END * 0.009144 * SUM(B.NHOOKS) AS AREA_SWEPT_KM2,
         MAX(GROUPING_CODE) AS GROUPING_CODE,
         MAX(AREA_KM2) AS AREA_KM2,
         MAX(SURVEY_ID) AS SURVEY_ID,
         MAX(SURVEY_SERIES_ID) AS SURVEY_SERIES_ID,
         MAX(SURVEY_DESC) AS SURVEY_DESC,
         MAX(YEAR) AS YEAR
      INTO #SETS
      FROM (
         SELECT FE_PARENT_EVENT_ID,
            FISHING_EVENT_ID
         FROM TRIP_SURVEY T
            INNER JOIN FISHING_EVENT FE ON
            T.TRIP_ID = FE.TRIP_ID
         WHERE T.SURVEY_ID = @sid AND
            FE_MINOR_LEVEL_ID IS NULL AND FE_PARENT_EVENT_ID IS NOT NULL) A
      INNER JOIN (
         SELECT FE_PARENT_EVENT_ID,
            COUNT(FISHING_EVENT_ID) AS NHOOKS
         FROM TRIP_SURVEY T
            INNER JOIN FISHING_EVENT FE ON
            T.TRIP_ID = FE.TRIP_ID
         WHERE T.SURVEY_ID = @sid AND
            FE_MINOR_LEVEL_ID IS NOT NULL
         GROUP BY FE_PARENT_EVENT_ID) B ON
      A.FISHING_EVENT_ID = B.FE_PARENT_EVENT_ID
      INNER JOIN (
         SELECT FE.FISHING_EVENT_ID,
            FE.GROUPING_CODE,
            YEAR(TP.TRIP_START_DATE) AS YEAR,
            G.AREA_KM2,
            S.SURVEY_ID,
            S.SURVEY_SERIES_ID,
            S.SURVEY_DESC
         FROM SURVEY S
            INNER JOIN TRIP_SURVEY T ON
            S.SURVEY_ID = T.SURVEY_ID
            INNER JOIN TRIP TP ON
            T.TRIP_ID = TP.TRIP_ID
            INNER JOIN FISHING_EVENT FE ON
            TP.TRIP_ID = FE.TRIP_ID
            INNER JOIN LONGLINE_SPECS LS ON
            FE.FISHING_EVENT_ID = LS.FISHING_EVENT_ID
            INNER JOIN GROUPING G ON
            FE.GROUPING_CODE = G.GROUPING_CODE
         WHERE T.SURVEY_ID = @sid AND
         ISNULL(LS.USABILITY_CODE,1) IN (0, 1, 2, 6)) FE ON
         A.FE_PARENT_EVENT_ID = FE.FISHING_EVENT_ID
      GROUP BY A.FE_PARENT_EVENT_ID

     -- Cross-product:
   SELECT FISHING_EVENT_ID, @spp AS SPECIES_CODE
   INTO #SETS_FISH
   FROM #SETS

   -- STEP 2: Get the catch for the sets/fish cross product
   --         Zero-weight sets are included
   SELECT SF.FISHING_EVENT_ID,
      SF.SPECIES_CODE,
      SUM(ISNULL(CATCH_WEIGHT,0)) AS CATCH_WEIGHT,
      SUM(ISNULL(CATCH_COUNT,0)) AS CATCH_COUNT
   INTO #CATCH
   FROM #SETS_FISH SF
      LEFT OUTER JOIN (
         SELECT S.FISHING_EVENT_ID,
            C.SPECIES_CODE,
            CATCH_WEIGHT,
            CATCH_COUNT
         FROM #SETS S
            INNER JOIN FISHING_EVENT_CATCH FEC ON
            S.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
            INNER JOIN CATCH C ON
            FEC.CATCH_ID = C.CATCH_ID) C
      ON SF.FISHING_EVENT_ID = C.FISHING_EVENT_ID AND
      SF.SPECIES_CODE = C.SPECIES_CODE
   GROUP BY SF.FISHING_EVENT_ID, SF.SPECIES_CODE

   -- STEP 3 (final): Put it all together
   -- Total time to execute is about 40 sec
   SELECT S.SURVEY_DESC,
      S.SURVEY_SERIES_ID,
      S.SURVEY_ID,
      S.YEAR,
      C.SPECIES_CODE,
      S.FISHING_EVENT_ID,
      S.GROUPING_CODE,
      S.SKATE_COUNT,
      S.HOOK_COUNT,
      C.CATCH_WEIGHT,
      C.CATCH_COUNT,
      C.CATCH_COUNT / S.AREA_SWEPT_KM2 AS DENSITY_PPKM2
   FROM #SETS S
      INNER JOIN #CATCH C ON
      S.FISHING_EVENT_ID = C.FISHING_EVENT_ID


GO

