USE [GFBioSQL]
GO

/****** Object:  StoredProcedure [dbo].[proc_catmat_sable]    Script Date: 11/21/2017 12:02:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[proc_catmat_sable] @sid INTEGER, @spp VARCHAR(3)
AS
   SET NOCOUNT ON

   -- Fishing event attributes for good (USABILITY_CODE = 0,1,2,6) sets:
   SELECT S.SURVEY_SERIES_ID,
      S.SURVEY_ID,
      S.SURVEY_DESC,
      TRS.TRIP_ID,
      YEAR(T.TRIP_START_DATE) AS [YEAR],
      FE.FISHING_EVENT_ID,
      FE.FE_MAJOR_LEVEL_ID,
      FE.FE_START_LATTITUDE_DEGREE + FE.FE_START_LATTITUDE_MINUTE / 60 AS LATITUDE,
      -(FE.FE_START_LONGITUDE_DEGREE + FE.FE_START_LONGITUDE_MINUTE / 60) AS LONGITUDE,
      FEG.GROUPING_CODE,
      FE.FE_BEGINNING_BOTTOM_DEPTH AS DEPTH_M,
      ISNULL(TS.TRAPS_FISHED_COUNT, TS.TRAPS_SET_COUNT) AS TRAP_COUNT
   INTO #SETS
   FROM SURVEY S
      INNER JOIN TRIP_SURVEY TRS ON
      S.SURVEY_ID = TRS.SURVEY_ID
      INNER JOIN TRIP T ON
      TRS.TRIP_ID = T.TRIP_ID
      INNER JOIN FISHING_EVENT FE ON
      T.TRIP_ID = FE.TRIP_ID
      LEFT JOIN TRAP_SPECS TS ON
      FE.FISHING_EVENT_ID = TS.FISHING_EVENT_ID
      INNER JOIN FISHING_EVENT_GROUPING FEG ON
      FE.FISHING_EVENT_ID = FEG.FISHING_EVENT_ID
      INNER JOIN SURVEY_GROUPING SG ON
      S.SURVEY_ID = SG.SURVEY_ID AND
      SG.GROUPING_CODE = FEG.GROUPING_CODE
   WHERE S.SURVEY_ID = @sid AND ISNULL(USABILITY_CODE,1) IN (0, 1, 2, 6, 12) AND FE.FE_PARENT_EVENT_ID IS NULL

   -- Cross-product:
   SELECT FISHING_EVENT_ID, @spp AS SPECIES_CODE
   INTO #SETS_FISH
   FROM #SETS

   -- STEP 2: Get the catch for the sets/fish cross product
   --         Zero-weight sets are included
   SELECT SF.FISHING_EVENT_ID,
      SF.SPECIES_CODE,
      SUM(ISNULL(CATCH_WEIGHT,0)) AS CATCH_WEIGHT,
      SUM(ISNULL(CATCH_COUNT,0)) AS CATCH_COUNT
   INTO #CATCH
   FROM #SETS_FISH SF
      LEFT OUTER JOIN (
         SELECT S.FISHING_EVENT_ID,
            C.SPECIES_CODE,
            CATCH_WEIGHT,
            CATCH_COUNT
         FROM #SETS S
            INNER JOIN FISHING_EVENT_CATCH FEC ON
            S.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
            INNER JOIN CATCH C ON
            FEC.CATCH_ID = C.CATCH_ID) C
      ON SF.FISHING_EVENT_ID = C.FISHING_EVENT_ID AND
      SF.SPECIES_CODE = C.SPECIES_CODE
   GROUP BY SF.FISHING_EVENT_ID, SF.SPECIES_CODE

   -- STEP 3 (final): Put it all together
   -- Total time to execute is about 40 sec
   SELECT S.SURVEY_SERIES_ID,
      S.SURVEY_ID,
      C.SPECIES_CODE,
      S.SURVEY_DESC,
      S.TRIP_ID,
      S.[YEAR],
      S.FISHING_EVENT_ID,
      S.FE_MAJOR_LEVEL_ID,
      S.LATITUDE,
      S.LONGITUDE,
      S.GROUPING_CODE,
      S.DEPTH_M,
      S.TRAP_COUNT,
      C.CATCH_WEIGHT,
      C.CATCH_COUNT,
      --C.CATCH_COUNT / 
      --   (S.TRAP_COUNT) AS CPUE_PPT
      C.CATCH_WEIGHT / S.TRAP_COUNT AS CPUE_PPT
   FROM #SETS S
      INNER JOIN #CATCH C ON
      S.FISHING_EVENT_ID = C.FISHING_EVENT_ID

GO

