USE [GFBioSQL]
GO

/****** Object:  StoredProcedure [dbo].[proc_survey_fish_species]    Script Date: 11/21/2017 12:06:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[proc_survey_fish_species] @survey_id INT
AS

   SET NOCOUNT ON
   
   SELECT DISTINCT(C.SPECIES_CODE) AS SPECIES_CODE,
      PacHarvest.dbo.INITCAP(SPECIES_DESC) AS SPECIES_NAME
   FROM SURVEY SV
      INNER JOIN TRIP_SURVEY TS ON
      SV.SURVEY_ID = TS.SURVEY_ID
      INNER JOIN FISHING_EVENT FE ON
      TS.TRIP_ID = FE.TRIP_ID
      INNER JOIN FISHING_EVENT_CATCH FEC ON
      FE.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
      INNER JOIN CATCH C ON
      FEC.CATCH_ID = C.CATCH_ID
      INNER JOIN SPECIES_SPP_GROUP SSG ON
      C.SPECIES_CODE = SSG.SPECIES_CODE
      INNER JOIN SPECIES S ON
      C.SPECIES_CODE = S.SPECIES_CODE
      INNER JOIN TRAWL_SPECS TSP ON
      FE.FISHING_EVENT_ID = TSP.FISHING_EVENT_ID
      INNER JOIN FISHING_EVENT_GROUPING FEG ON
      FE.FISHING_EVENT_ID = FEG.FISHING_EVENT_ID
      INNER JOIN SURVEY_GROUPING SG ON
      SV.SURVEY_ID = SG.SURVEY_ID AND
      SG.GROUPING_CODE = FEG.GROUPING_CODE
   WHERE CATCH_WEIGHT > 0.5 AND SPP_GROUP_CODE = 1 AND
      SV.SURVEY_ID = @survey_id AND
      SPECIES_DESC NOT LIKE '%S' AND
      ISNULL(USABILITY_CODE,1) IN (0, 1, 2, 6)

GO

