-- Drop stored procedure if it already exists
IF EXISTS (
  SELECT * 
    FROM INFORMATION_SCHEMA.ROUTINES 
   WHERE SPECIFIC_SCHEMA = N'dbo'
     AND SPECIFIC_NAME = N'proc_jig_survey_fish_species'
)
   DROP PROCEDURE proc_jig_survey_fish_species
GO

CREATE PROCEDURE proc_jig_survey_fish_species @survey_id INT
AS

   SET NOCOUNT ON
   
   SELECT DISTINCT(C.SPECIES_CODE) AS SPECIES_CODE,
      PacHarvest.dbo.INITCAP(SPECIES_DESC) AS SPECIES_NAME
   FROM SURVEY SV
      INNER JOIN TRIP_SURVEY TS ON
      SV.SURVEY_ID = TS.SURVEY_ID
      INNER JOIN FISHING_EVENT FE ON
      TS.TRIP_ID = FE.TRIP_ID
      INNER JOIN FISHING_EVENT_CATCH FEC ON
      FE.FISHING_EVENT_ID = FEC.FISHING_EVENT_ID
      INNER JOIN CATCH C ON
      FEC.CATCH_ID = C.CATCH_ID
      INNER JOIN SPECIES_SPP_GROUP SSG ON
      C.SPECIES_CODE = SSG.SPECIES_CODE
      INNER JOIN SPECIES S ON
      C.SPECIES_CODE = S.SPECIES_CODE
      LEFT JOIN HANDLINE_SPECS HS ON
      FE.FISHING_EVENT_ID = HS.FISHING_EVENT_ID
      INNER JOIN FISHING_EVENT_GROUPING FEG ON
      FE.FISHING_EVENT_ID = FEG.FISHING_EVENT_ID
      INNER JOIN SURVEY_GROUPING SG ON
      SV.SURVEY_ID = SG.SURVEY_ID AND
      SG.GROUPING_CODE = FEG.GROUPING_CODE
   WHERE CATCH_COUNT > 0 AND SPP_GROUP_CODE = 1 AND
      SV.SURVEY_ID = @survey_id AND
      TAXONOMIC_RANK = 'Species' AND
      ISNULL(USABILITY_CODE,1) IN (0, 1, 2, 6, 12)
GO

EXEC proc_jig_survey_fish_species 490
GO